<?php

namespace Sunnysideup\EcommerceCustomProductLists\Model;

use SilverStripe\Forms\ReadonlyField;
use SilverStripe\ORM\DataObject;

/**
 * Automatically maintained change log for a {@see CustomProductList}.
 *
 * One row per *distinct* change (identified by Signature, unique per list).
 * Re-applying the same change does not create a second row - instead the
 * existing row is "touched" (Occurrences++, which bumps LastEdited), so with
 * the LastEdited ASC default sort it moves to the bottom = the last thing done.
 *
 * "When" is covered by the built-in Created (first applied) and LastEdited
 * (last applied) fields, so there is no separate Applied column.
 *
 * Rows are created/updated programmatically from CustomProductList only; the
 * CMS shows them read-only.
 *
 * @property string $Type
 * @property string $Signature
 * @property string $Description
 * @property int    $Occurrences
 * @property int    $CustomProductListID
 * @method \Sunnysideup\EcommerceCustomProductLists\Model\CustomProductList CustomProductList()
 */
class CustomProductListChange extends DataObject
{
    private static $table_name = 'CustomProductListChange';

    private static $db = [
        'Type' => 'Varchar(50)',
        'Signature' => 'Varchar(255)',
        'Description' => 'Varchar(255)',
        'Occurrences' => 'Int',
    ];

    private static $has_one = [
        'CustomProductList' => CustomProductList::class,
    ];

    private static $indexes = [
        // one entry per (list, signature) - guarantees we never duplicate.
        'SignaturePerList' => [
            'type' => 'unique',
            'columns' => ['CustomProductListID', 'Signature'],
        ],
        'LastEdited' => true,
    ];

    // oldest first, most-recently-applied last (LastEdited is bumped on each redo).
    private static $default_sort = 'LastEdited ASC, ID ASC';

    private static $summary_fields = [
        'Created.Nice' => 'First applied',
        'LastEdited.Ago' => 'Last applied',
        'Type' => 'Type',
        'Description' => 'Change',
        'Occurrences' => 'Times',
    ];

    private static $field_labels = [
        'Created' => 'First applied',
        'LastEdited' => 'Last applied',
        'Occurrences' => 'Times applied',
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        // Signature is an internal de-dupe key - not useful to editors.
        $fields->removeByName('Signature');

        // Created/LastEdited are not scaffolded by default; add them read-only.
        $fields->addFieldsToTab(
            'Root.Main',
            [
                ReadonlyField::create('CreatedNice', $this->fieldLabel('Created'), $this->dbObject('Created')->Nice()),
                ReadonlyField::create('LastEditedNice', $this->fieldLabel('LastEdited'), $this->dbObject('LastEdited')->Nice()),
            ],
            'Type'
        );

        return $fields;
    }

    /**
     * History is generated by code, never created by hand in the CMS.
     * (write() is not gated by canCreate(), so programmatic logging still works.)
     */
    public function canCreate($member = null, $context = [])
    {
        return false;
    }

    public function canEdit($member = null)
    {
        return false;
    }

    public function canView($member = null)
    {
        return $this->CustomProductList()->canView($member);
    }

    public function canDelete($member = null)
    {
        return $this->CustomProductList()->canEdit($member);
    }
}
