---
Name: ecommerce_custom_product_lists
Before:
  - '#app'
After:
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
---
Sunnysideup\Ecommerce\Cms\ProductConfigModelAdmin:
  managed_models:
    - Sunnysideup\EcommerceCustomProductLists\Model\CustomProductList
