---
Name: ecommerce_custom_product_lists
Before: 'app/*'
After:
  - 'framework/*'
  - 'cms/*'
  - 'ecommerce/*'
---
Sunnysideup\Ecommerce\Cms\ProductConfigModelAdmin:
  managed_models:
    - Sunnysideup\EcommerceCustomProductLists\Model\CustomProductList
